const { createClient } = require('@supabase/supabase-js');
const config = require('../../config');
const { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits } = require('discord.js');

const supabase = createClient(config.supabaseUrl, config.supabaseServiceRoleKey, { auth:{persistSession:false,autoRefreshToken:false} });
const giveawayEntries = new Map();
const giveawayTimers = new Map();

function parseDuration(input){const m=String(input||'').trim().match(/^(\d+)\s*(s|m|h|d|w)$/i);if(!m)return null;const n=Number(m[1]),u=m[2].toLowerCase(),x={s:1000,m:60000,h:3600000,d:86400000,w:604800000}[u];const ms=n*x;return Number.isSafeInteger(ms)&&ms>0?ms:null;}
function formatDuration(ms){let s=Math.floor(ms/1000),w=Math.floor(s/604800);s%=604800;let d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;const a=[];if(w)a.push(`${w}w`);if(d)a.push(`${d}d`);if(h)a.push(`${h}h`);if(m)a.push(`${m}m`);if(s||!a.length)a.push(`${s}s`);return a.join(' ');}
async function saveState(messageId,state){const row={message_id:String(messageId),guild_id:String(state.guildId),channel_id:String(state.channelId),prize:state.prize,winners:state.winners,ends_at:state.endsAt,entries:[...state.entries]};const {error}=await supabase.from('giveaways').upsert(row,{onConflict:'message_id'});if(error)throw error;}
async function deleteState(messageId){const {error}=await supabase.from('giveaways').delete().eq('message_id',String(messageId));if(error)console.error('Giveaway DB delete error:',error.message);}
async function finishGiveaway(messageId,client){const state=giveawayEntries.get(String(messageId));if(!state)return;giveawayEntries.delete(String(messageId));const t=giveawayTimers.get(String(messageId));if(t)clearTimeout(t);giveawayTimers.delete(String(messageId));await deleteState(messageId);try{const channel=await client.channels.fetch(state.channelId);const message=await channel.messages.fetch(messageId);const pool=[...state.entries],winners=[];while(winners.length<Math.min(state.winners,pool.length)){const i=Math.floor(Math.random()*pool.length);winners.push(pool.splice(i,1)[0]);}const winnerText=winners.length?winners.map(id=>`<@${id}>`).join(', '):'No valid entries.';const old=message.embeds[0];const embed=old?EmbedBuilder.from(old).setTitle(`🎁 ${state.prize} — ENDED`).setDescription(`## 🎉 Giveaway Ended!\n\n🎁 **Prize:** ${state.prize}\n🏆 **Winners:** ${state.winners}\n👥 **Entries:** ${state.entries.size}\n\n🥳 **Winner(s):** ${winnerText}`).setFooter({text:'Vehicle Life • Giveaway ended'}).setTimestamp():new EmbedBuilder().setTitle(`🎁 ${state.prize} — ENDED`).setDescription(`🥳 **Winner(s):** ${winnerText}`).setTimestamp();await message.edit({embeds:[embed],components:[]});}catch(err){console.error('Giveaway finish error:',err.message);}}
function schedule(messageId,client,endsAt){const ms=Math.max(0,endsAt-Date.now());const timer=setTimeout(()=>finishGiveaway(messageId,client),Math.min(ms,2147483647));giveawayTimers.set(String(messageId),timer);}
async function init(client){const {data,error}=await supabase.from('giveaways').select('*');if(error){console.error('Giveaway restore error:',error.message);return;}for(const row of data||[]){const id=String(row.message_id);if(Number(row.ends_at)<=Date.now()){await finishGiveaway(id,client);continue;}const state={guildId:String(row.guild_id),channelId:String(row.channel_id),prize:row.prize,winners:Number(row.winners),endsAt:Number(row.ends_at),entries:new Set(Array.isArray(row.entries)?row.entries:[])};giveawayEntries.set(id,state);schedule(id,client,state.endsAt);}console.log(`Restored ${giveawayEntries.size} active giveaway(s).`);}

module.exports={giveawayEntries,init,saveState,data:new SlashCommandBuilder().setName('giveaway').setDescription('Create a giveaway').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(sub=>sub.setName('create').setDescription('Create a giveaway').addStringOption(o=>o.setName('prize').setDescription('Giveaway prize').setRequired(true)).addStringOption(o=>o.setName('duration').setDescription('Example: 1h, 24h, 7d').setRequired(true)).addIntegerOption(o=>o.setName('winners').setDescription('Number of winners').setMinValue(1).setMaxValue(20).setRequired(true))),
async execute(interaction){const prize=interaction.options.getString('prize'),duration=interaction.options.getString('duration'),winners=interaction.options.getInteger('winners'),durationMs=parseDuration(duration);if(!durationMs)return interaction.reply({content:'❌ Invalid duration. Use `30s`, `10m`, `1h`, `24h`, or `7d`.',ephemeral:true});const endsAt=Date.now()+durationMs;const embed=new EmbedBuilder().setColor(0x5865F2).setTitle(`🎁 ${prize}`).setDescription(`## 🎉 Giveaway is Live!\n\nClick the button below to enter!\n\n🎁 **Prize:** ${prize}\n🏆 **Winners:** ${winners}\n⏱️ **Duration:** ${formatDuration(durationMs)}\n⏰ **Ends:** <t:${Math.floor(endsAt/1000)}:R>\n\n👥 **Entries:** 0`).setFooter({text:'Vehicle Life • Good luck! 🍀'}).setTimestamp();const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('giveaway_join').setLabel('🎉 Join Giveaway').setStyle(ButtonStyle.Success));await interaction.reply({embeds:[embed],components:[row]});const msg=await interaction.fetchReply();const state={guildId:interaction.guildId,channelId:interaction.channelId,prize,winners,endsAt,entries:new Set()};giveawayEntries.set(msg.id,state);try{await saveState(msg.id,state);}catch(err){giveawayEntries.delete(msg.id);await msg.edit({content:'❌ Giveaway could not be saved. Run `supabase-setup.sql` first.',components:[]}).catch(()=>{});return;}schedule(msg.id,interaction.client,endsAt);}}
